// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdriwslcorpedrvjqfxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtkcml3c2xjb3JwZWRydmpxZnh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyMDI0ODIsImV4cCI6MjA1MTc3ODQ4Mn0.lixldXHlUH7TNe3T2q53t1F6PHhUo2SN-A5b-FdDNHs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);